config/routes.rb
Rails.application.routes.draw do
  root to: "questions#index"

  resources :questions do 
    put 'hide', on: :member
    put 'visible', on: :member
  end

  resources :users do 
    get 'confirm_email', on: :member
  end
  
  resource :session, only: %i[new create destroy]
  resources :hashtags, param: :name, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  has_many :hashtag_appearances, dependent: :delete_all
  has_many :questions, through: :hashtag_appearances, dependent: :delete_all

  validates :name, presence: true, uniqueness: true
end

app/models/hashtag_appearance.rb
class HashtagAppearance < ApplicationRecord
  belongs_to :hashtag
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: "User", foreign_key: :author_id
  
  has_many :hashtag_appearances, dependent: :delete_all
  has_many :hashtags, through: :hashtag_appearances, dependent: :delete_all

  before_create :hashtag_question 
  
  validates :body, presence: true, length: { maximum: 280 }
  validates :body, presence: true, length: { maximum: 280 }

  def hashtag_question
    hashtags = self.body.scan(/#[[:word:]-]+/).map { |tag| Hashtag.find_or_create_by!(name: tag.downcase) }

    self.hashtags << hashtags
  end
end

app/models/user.rb
require 'securerandom'

class User < ApplicationRecord
  has_secure_password

  extend FriendlyId
  include Gravtastic
  
  gravtastic(secure: true, filetype: :png, size: 70, default: 'identicon')
  
  before_create :confirm_token do
    self.confirm_token = SecureRandom.uuid if self.confirm_token.blank? 
  end
  
  before_validation :downcase
  
  has_many :questions, dependent: :delete_all
  
  friendly_id :nickname, use: :slugged

  validates :color,
    format: { with: /\A#\h{3}{1,2}\z/ }

  validates :email, presence: true, uniqueness: true,
    format: { with: /\A[^@\s]+@[^@\s]+\z/ }
    
  validates :nickname, presence: true, uniqueness: true,
    format: { with: /\A[a-zA-Z0-9_]{1,40}\z/ }


  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    
    save!(validate: false)
  end

  private
  
  def downcase
    nickname.downcase!
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.friendly.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: I18n.t("controller.you_are_forbidden")
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :set_user, only: %i[show]
  
  def show
    @questions = @hashtag.questions
  end

  private

  def set_user
    @hashtag = Hashtag.friendly.find(params[:name])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update destroy edit]
  before_action :set_question_for_current_user, only: %i[edit update]
  after_action :hashtag_answer, only: %i[update]
  before_action :hidden?, only: %i[hide visible destroy]

  def create
    questions_params = params.require(:question).permit(:body, :user_id)

    @question = Question.new(questions_params)
    
    @question.author = current_user
    @question.hidden = true
    
    if @question.save
      redirect_to user_path(@question.user), notice: I18n.t("controller.new_question_create!")
    else
      flash[:alert] = I18n.t("controller.the_form_has_been_filled_out_incorrectly")

      render :new
    end
  end

  def update
    if @question.author == @question.user
      questions_params = params.require(:question).permit(:body, :answer)
    elsif @question.author != @question.user
      questions_params = params.require(:question).permit(:answer)
    end

    @question.update(questions_params)

    if @question.save
      redirect_to user_path(@question.user), notice: I18n.t("controller.question_save")
    else
      render :edit
    end
  end

  def destroy  
    @user = @question.user

    @question.destroy

    redirect_to user_path(@user), status: :see_other, notice: I18n.t("controller.question_delete")
  end

  def show    
    @question = Question.find(params[:id])
  end
  
  
  def index
    @questions = Question.order(created_at: :desc).first(10)
    
    @users = User.order(created_at: :desc).last(10)

    @hashtags = Hashtag.order(created_at: :desc).first(30)
  end
  
  def new
    @user = User.friendly.find(params[:user_id])
    @question = Question.new(user: @user)
  end
  
  def edit
  end
  
  def visible
    @question.update(hidden: false)

    redirect_to root_path
  end
  
  def hide
    @question.update(hidden: true)
    
    redirect_to root_path
  end

  private

  def hashtag_answer
    hashtags_answer = @question.answer.scan(/#[[:word:]-]+/).map! { |tag| Hashtag.find_or_create_by!(name: tag.downcase) }

    @question.hashtags << hashtags_answer
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def hidden?
    @question = Question.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    # debugger
    
    if user != nil && user.email_confirmed == true
      session[:user_id] = user.id
        
      redirect_to root_path, notice: t(".your_login")
    elsif user == nil
      flash[:alert] = t(".error_email_address_or_password")

      render :new
    elsif user != nil && user.email_confirmed == false
      flash[:alert] = t(".please_active_your_account")

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: t(".you_are_log_out")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]


  def new
    session[:current_time] = Time.now

    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      UserMailer.new_user(@user).deliver_now

      flash[:notice] = t(".registration_completed_successfully")
      
      redirect_to root_path
    else
      flash.now[:alert] = t(".registration_fields_filled_out_incorrectly")

      render :new
    end
  end

  def confirm_email
    @user = User.find_by_confirm_token(params[:id])

    if @user.email_confirmed == false
      @user.email_activate

      flash[:notice] = t(".welcome")
      session[:user_id] = @user.id

      redirect_to root_path
    else
      flash[:alert] = t(".success_confirmed_email") 

      redirect_to root_path
    end
  end

  def update
    if @user.update(user_params)
      UserMailer.new_user_update(@user).deliver_now

      redirect_to root_path, notice: I18n.t("controller.update_user_data")
    else
      flash.now[:alert] = I18n.t("controller.save_error")

      render :edit
    end
  end

  def edit
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: I18n.t("controller.account_deleted")
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    
    @question = Question.new(user: @user)
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation, :color
    )
  end

  def authorize_user
    redirect_with_alert unless current_user == @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1..4 then one
    else
      many
    end
  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def display_nickname(user)
    unless user == nil
      "@#{user.nickname}"
    end
  end
end

app/views/hashtags/index.html.erb
<div class="mb__sm text__pre__line">
  <%= @question.body %>
  <div class="mt-sm g">
    <% @question.hashtags.each do |hashtag|%>
      <%= link_to hashtag.name, hashtags_path %>
    <% end %>
  </div>
</div>

app/views/hashtags/show.html.erb
<div class="container">
<h2 class="mb"><%= link_to @hashtag.name %></h2>

  <% @questions.uniq.each do |question| %>
    <p class="g"><%= question.body %><p>
  <% end %>
  
<p class="mt"><%= link_to "All questions", questions_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <script type="text/javascript" charset="utf-8" src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="js/hidden.js"></script>
    
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar" style="background: <%= current_user&.color || '#370617' %>">
        <p class="title__sm text__bold"><%= link_to t(".ask_me!"), root_path %></p>
        <div>
          <% if current_user.present? %>
            <%= link_to display_nickname(current_user), user_path(current_user), class: "mr__sm text__bold" %>
            <%= button_to 'Exit', session_path, method: :delete, class: 'button button__yellow' %>
          <% else %>
            <%= link_to "Registration", new_user_path, class: 'button button__yellow mr__sm' %>
            <%= link_to 'Login', new_session_path, class: 'button button__yellow'  %>
          <% end %>
        </div>
      </div>
      <% if flash[:notice].present? %>
        <p class="mb mt message__notice"><%= flash[:notice]%></p>
      <% elsif flash[:alert].present? %>
        <p class="mb mt message message__alert"><%= flash[:alert]%></p>
      <% end %>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/partials/_form_errors.html.erb
<%= errors = model.errors %>

<% if errors.any? %>
  <div class="alert alert-danger">
    <div class="lead buffer-bottom">
      <%= I18n.t("errors.messages.not_saved", count: errors.count)%>
    </div>
    <ul>
      <% errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/questions/_form.html.erb
<% if question.errors.any? %>
  <div class="mt">
    <% question.errors.full_messages.each do |message| %>
      <p class="mb__sm text__red"><%= message %></p>
    <% end %>
  </div>
<% end %>

<%= form_with model: question, data: {turbo: false} do |form| %>
  <%= form.hidden_field :user_id %>

  <p><%= form.label :body, 'Question text' %></p>
  <p><%= form.text_area :body, rows: 5, class: 'form__text__area' %></p>
  
  <% if question.persisted? %>
    <p class="mt"><%= form.label :answer, 'Answer' %></p>
    <p><%= form.text_area :answer, rows: 5, class: 'form__text__area' %></p>
  <% end %>

  <div class="back">
    <p class="mt"><%= form.submit "Save", class: 'button button__main' %></p>
    <p class="mt ml"> <%= 'or'  %></p>
    <%= link_to 'back', :back, class: 'ml'  %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<% if question.errors.any? %>
  <div class="mt">
    <% question.errors.full_messages.each do |message| %>
      <p class="mb__sm text__red"><%= message %></p>
    <% end %>
  </div>
<% end %>

<div class="mt__sm container">
  <div class="text__sm question__header">
    <div class="text__grey">
      <span><%= t('.question_for') %>
        <%= link_to "@#{question.user.nickname}", user_path(question.user) %></span>
    </div>
  </div>

<div class="mb__sm text__pre__line">
  <% if question.hidden? %>
    <div class="description-question">
      <%= question.body %>
      <div class="mt-sm g">
        <% question.hashtags.uniq.each do |tag| %>
          <%= link_to tag.name, hashtag_path(tag.slug) %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<% if question.answer.present? %>
  <div class="mb__sm text__dark__red answer_text_color">
    <%= question.answer %>
  </div>
<% end %>

<div class="text__sm question__footer">
  <div class="text__grey">
    <% if question.author.present? %>
      <span><%= t('.question_from') %>
        <%= link_to display_nickname(question.author), user_path(question.author_id) %></span>
    <% end %>
    <%= l(question.created_at, format: :short) %>
  </div>

  <div>
    <% if current_user == question.user %>
      <% edit_icon = (question.answer.present? ? 'pencil' : 'reply') %>
      <%= link_to fa_icon(edit_icon), edit_question_path(question),
        title: "Change question" %>
    <% end %>


    <% if current_user.present? && current_user == question.author %>

      <%= link_to fa_icon('trash-o'), question_path(question),
        data: { turbo_method: "delete", turbo_confirm: "Are you sure?" }  %>
      <% if question.hidden? %>
        <%= button_to fa_icon('eye'), visible_question_path(question), title: 'Show question?', method: :put, class: "description" %>
        <%= link_to "Question #{question.id}", question_path(question) %>
      <% else %>
        <%= button_to fa_icon('eye-slash'), hide_question_path(question), title: 'Hidde question?', method: :put %>
        <span class="opacity"><%= link_to "Question #{question.id}", question_path(question) %></span>
      <% end %>
    <% end %>
  </div>

</div>

</div>

app/views/questions/_users.html.erb
<% unless @users.empty? %>
  <div class="container mt__sm">
    <h2 class="title__lg">
      <div class="container">
        <h5 class="mb__sm text__grey empty__state"><%= t('.all_users') %></h5>
        <div class="user__all" >
          <% @users.each do |user| %>
            <a href="<%= user_path(user) %>">
              <p  class="text__bold" ><%= image_tag user.gravatar_url, title: "@#{user.nickname}", class: 'rounded' %></p>
            </a>
          <% end %>
        </div>
      </div>
    </h2>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title__lg mb">Edit question <%= @question.id %></h2>
  <hr>
  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="mt-sm g container">
  <% @hashtags.each do |hashtag|%>
    <% unless hashtag.questions.blank? %>
      <%= link_to hashtag.name, hashtag_path(hashtag.slug) %>
    <% end %>
  <% end %>
</div>

<%= render 'users' %>

<% unless @questions.count == 0 %>
  <div class="container mt__sm">
    <h2 class="title__lg">
      <%= @questions.count %>
      <%= inclination(@questions.count, 'question', 'questions') %>
    </h2>
  </div>
<% end %>


<% if @questions.count == 0 && current_user.present? %>
  <%= render 'users/user_login' %>
<% elsif @questions.count == 0%>
  <%= render 'users/user_registration' %>
<% else %>
  <%= render @questions %>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title__lg mb__sm">New questions</h2>
  <% unless display_nickname(@user) == nil %>
    <p class="mb">for <%= link_to display_nickname(@user), user_path(@user) %></p>
  <% end %>
  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title__lg mb">Questions  - <%= @question.id %></h2>
  <p class="mt__sm"><%= link_to "All questions", questions_path %></p>
</div>

<div class="container mt__sm">
  <%= render 'question', question: @question %>
</div>

app/views/users/_user_asks.html.erb
<div class="mt__sm mb__lg empty__state container">
  <h2 class="title__lg text__grey">No one wrote to you...</h2>
  <%= image_tag("seach.png", alt: "Ask me?", class: "menu__icon") %>
  <h2 class="text__grey title__md mb__md">Write first.</h2>
  <%= link_to "Add question", users_path(@users), class: "button button__blue" %>
</div>

app/views/users/_user_avatar.html.erb
<div>
  <a href="<%= user_path(user) %>">
    <%= image_tag user.gravatar_url, title: "@#{user.nickname}", class: 'rounded' %>
  </a>
</div>

app/views/users/_user_login.html.erb
<div class="mt__sm mb__lg empty__state container">
  <h2 class="title__lg text__grey">Oops, question field is empty....</h2>
  <%= image_tag("seach.png", alt: "Ask me?", class: "menu__icon") %>
  <h2 class="text__grey title__md mb__md">Ask a question, be the first!!!</h2>
  <%= link_to "Add question", users_path(@users), class: "button button__blue" %>
</div>

app/views/users/_user_registration.html.erb
<div class="mt__sm mb__lg empty__state container">
  <h2 class="title__lg text__grey">Oops, question field is empty....</h2>
  <%= image_tag("seach.png", alt: "Ask me?", class: "menu__icon__opacity") %>
  <h2 class="text__grey title__sm mb__md">Send a message to your new friends</h2>
  <h2 class="title__sm mb__md">Register and ask</h2>
  <%= link_to "Registration", new_user_path, class: "button button__blue" %>
</div>

app/views/users/_users_choice.html.erb
<% if @users.count == 0 %>
  <h2 class="title__lg mb">
    No new users
    </h2>
      <div class="users__box">
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: {user: user} %>
    <% end %>
  </div>
<% else %>
  <h2 class="title__lg mb">
    All users
  </h2>
   <div class="users__box">
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: {user: user} %>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title">User editing<h2>

  <% if @user.errors.any? %>
   <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb__sm text__red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="mt">
    <p><%= image_tag @user.gravatar_url, title: "@#{@user.nickname}", class: 'rounded' %></p>
    <p class="text__sm">To add or change an avatar - register on
      <%= link_to "Gravatar", 'https://gravatar.com' %> and upload a photo</p>
  </div>

  <div class="mt">
    <%= form_with model: @user, data: { turbo: false } do |form| %>
      <p><%= form.label :name, "Name" %></p>
      <p><%= form.text_field :name, class: "form__text__field" %></p>

      <p class="mt"><%= form.label :nickname, "Nickname on the site" %></p>
      <p><%= form.text_field :nickname, class: "form__text__field" %></p>

      <p class="mt__lg text__sm">If you don't want to change your password, leave the field blank.</p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: "form__text__field" %></p>

      <p class="mt"><%= form.label :password, 'Password' %></p>
      <p><%= form.password_field :password, class: "form__text__field" %></p>

      <p class="mt"><%= form.label :password_confirmation, 'Password confirmation' %></p>
      <p><%= form.password_field :password_confirmation, class: "form__text__field" %></p>
      
      <p class="mt"><%= form.color_field :color %>
      <%= form.label :color, 'Choose color header', class: "title__sm text__grey" %></p>
  
      <p class="mt__lg">
        <%= form.submit "Save", class: "button button__main" %>
        <span class="text__sm">or <%= link_to "Back", :back %></span>
      </p>

    <% end %>
  </div>
  <div class="mt__lg">
    <%= button_to "Delete profile", user_path(@user),
    method: :delete,
    form: {data: {turbo_confirm: "Are you sure?"}},
    class: 'text__red text__sm' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2 class="title__lg mb__sm text__grey empty__state">All users</h2>
  <h2 class="title__sm mb__lg empty__state"><%= t('.who_do_you_want_to_ask_a_question?') %></h2>
  <div class="user__all" >
    <% @users.each do |user| %>
    <a href="<%= user_path(user) %>">
      <p  class="text__bold" ><%= image_tag user.gravatar_url, title: "@#{user.nickname}", class: 'rounded' %></p>
    </a>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Join and ask</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb__sm text__red"><%= message %></p>
      <% end %>
    </div>
  <% end %>
  
  <div class="mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p><%= form.label :name, "Your name?" %></p>
      <p><%= form.text_field :name, class: "form__text__field" %></p>
      <p class="mt"><%= form.label :nickname, "Nickname on the site?" %></p>
      <p><%= form.text_field :nickname, class: "form__text__field" %></p>
      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: "form__text__field" %></p>
      <p class="mt"><%= form.label :password %></p>
      <p><%= form.password_field :password, class: "form__text__field" %></p>
      <p class="mt"><%= form.label :password_confirmation %></p>
      <p><%= form.password_field :password_confirmation, class: "form__text__field" %></p>
      <p class="mt__lg"><%= form.submit "Registration", class: "button button__main" %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user__box">

<div class="mt">
  <%= render partial: 'users/user_avatar', locals: { user: @user } %>
</div>

  <% if current_user == @user %>
    <p class="mt mb__lg">
      <%= link_to fa_icon('pencil'), edit_user_path(@user) %>
    </p>
  <% end %>


  <p class="text__bold mt mb__lg">@<%= @user.nickname %></p>
   <p class="text-sm mb">Чтобы добавить или поменять аватар — зарегистрируйтесь на <%= link_to "Gravatar", 'https://gravatar.com' %> и загрузите фото</p>
  </div>

<div class="container">
  <%= link_to "Ask me", new_question_path(user_id: @user.id),
    class: "button button__yellow" %>

  <p class="mt">
    <%= render 'questions/form', question: @question %>
  </p>
</div>


<div class="container mt__sm">
  <h2 class="title__lg">
    <%= @questions.count %>
    <%= inclination(@questions.count, 'question', 'questions') %>
  </h2>
</div>

<div class="mt__sm container">
<% if @questions.count == 0 && current_user.present?  %>
  <%= render "user_asks" %>
<% else %>
  <% @questions.each do |question| %>
    <%= render question %>
  <% end %>
<% end %>
</div>